version: '2'
services:
  web:
    build: .
    volumes:
      - .:/var/www/emprego-ja
    ports:
      - "80:80"
    command: 'rails s -b 0.0.0.0 -p 80'
    links:
      - db
  db:
    image: postgres
